"""Shared path conventions for coro.recipes scripts.

A single source for the default artifacts root keeps every recipe's
``--out-dir`` default consistent without copy-pasting the same ``Path(...)``
across modules -- see ``coro/recipes/__init__.py``'s module docstring for
why this location, not ``.tmp/``.
"""

from __future__ import annotations

from pathlib import Path

RECIPE_ARTIFACTS_DIR = Path("recipe-artifacts")
"""Default root for every recipe's generated output.

Resolved relative to the current working directory (recipes are meant to be
run from the repo root, same convention ``.tmp/`` scripts already used).
Gitignored -- never commit anything under here; artifacts here can always
be regenerated by re-running the recipe that produced them.
"""
